apiVersion: v1
kind: Service
metadata:
  name: cuckoo
  namespace: cuckoo
  labels:
    app: cuckoo
spec:
  type: ClusterIP
  selector:
    app: cuckoo
  ports:
    - name: http
      port: 80
      targetPort: http
